# Generated by Django 5.1.1 on 2024-10-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_date_opened_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
