# Generated by Django 5.1.1 on 2024-10-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("dateOpened", models.DateField()),
                ("status", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
